IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Rules' AND xtype='U')
CREATE TABLE Rules (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    NovelId INT NOT NULL FOREIGN KEY REFERENCES Novels(Id) ON DELETE CASCADE,
    SortOrder INT NOT NULL DEFAULT 0,
    Category NVARCHAR(100),
    Content NVARCHAR(MAX),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);
